### ISSUE TITLE
쿠버네티스

### ISSUE THREAD

**Issue by kgneng2** [kgneng2/blokg#22]
# overview
- k8s 개요
- ncc 교육 소개

# kubernetes 는 왜 hot 한가? 
- 마이크로 서비스로 세분화 되었고 인프라 변경에 따른 배포 방식이 달라 졌다
- 환경에 영향을 받지 않고 배포를 할 수 있다. 
- 같은 서버 앱끼리 충돌을 막아줄수있다
- 제 노트북에서는 되는데 왜 개발서버에선 안되죠? 개발에선 잘도는데 왜 리얼에 배포하면 안되죠? 란 질문을 없앨수 있다?!
- 도커도 되는데 왜 굳이 쓰나? (여러개 노드에서 도커를 실행시킬수 있기 때문이다) 
- 서버 리소스에 영향을 최소화 하기 위해서 사용한다
- scaling 에 유리하다
- 마이크로서비스 배포시 어려움을 어느정도 해결해준다 (많이 배포해야되는데 이를 관리하는걸 편리하게해줌)

# 컨테이너는 뭘까요?
![image](https://media.oss.navercorp.com/user/1592/files/ce5baa80-ec55-11e9-9af9-7d5d43e6eab5)

![image](https://media.oss.navercorp.com/user/1592/files/f1398f00-ec54-11e9-8d9c-c65d60a61075)

- VM을 사용할수 있겠지만 VM은 오버헤드가 크며 프로세스 수가 많아짐에 따라 리소스 관리가 어려움
- 컨테이너는 어떻게 격리시키나? [별거없다](https://pages.oss.navercorp.com/naver-container-cluster/docs/0/1.isolation/)
   - 리눅스 namespace로 분리
   - 리눅스 컨트롤 그룹
- Namespace 로 격리된 프로세스들은 같은 eth0 이더라도 서로 다른 Network Resource 를 사용하게 된다.
- cgroup 으로 묶인 프로세스들은 리소스 별로 정해진 량만 사용하게 설정할 수 있다.

# 그럼 이제 쿠버네티스는 뭘까요?
- 쿠버네티스가 컨테이너 운영을 관리해주는 플랫폼이다.
- 컨테이너 운영은 뭘까? 컨테이너를 운영하려면 모니터링 , 스케줄링 , lifecycle 등을 관리해주어야한다.
- 개발, 배포, 관리를 단순하게 해주도록 도와줌
- 클러스터 크기는 상관없고 추가 클러스터 노드들은 그냥 사용가능한 리소스를 의미한다

![image](https://media.oss.navercorp.com/user/1592/files/a3f53180-ee8f-11e9-93ff-6c4bf9def75b)

- 중앙(master)에 api서버와 상태 저장소를 두고 각 노드의 에이전트(kubelte)와 통신하는 단순한 구조
- master node
  - 전체 구버네티스 시스템을 관리하고 통제하는 컨트롤 플레인을 관장한다.
  - 죽으면 클러스터 관리가 되지 않기 때문에 3대로 구성한다.
- worker node
  - 실제 배포한 어플리케이션 담당
  - 마스터와 통신하며 pod생성 및 네트워크, 볼륨을 설정한다. 

좀 더 자세한 아키텍쳐는 아래에서 진행한다.

## 쿠버네티스 오브젝트 
- Pod(어플리케이션), Service(로드 밸런서), Volume(디스크), Namespace(패키지명) 를 오브젝트라 부름

### Pod
- **컨테이너화된 어플리케이션**
- 가장 기본적인 배포 단위, 컨테이너를 포함하는 단위
- 하나이상의 컨테이너를 포함한다. 하지만 일반적으로 단일 컨테이너만 포함한다. 
- 포드에 여러 컨테이너가 포함돼 있을때 항상 포드 전부가 단일 워커 노드에서 실행된다. -> 스케일링 , 스케줄링, 리소스 때문에
- Pod 내의 컨테이너는 Ip, port를 공유함. (동일한 네트워크에서 실행되기때문에)
- Pod 내에 배포된 컨테이너간에는 디스크 볼륨을 공유할 수 있다. -> 다른 컨테이너에 있는 파일을 읽어올수 있음.
- Node > Pod > Container

#### 여러 프로세스 실행시 왜 한개의 컨테이너 보다 다수의 컨테이너가 유리할까?
- 컨테이너가 한컨테이너당 하나의 프로세스만 실행하도록 설계되었기 때문
- 모든 프로세스가 표준 로그출력 할경우 어떤 프로세스가 로그를 남긴지 모른다 ^^:
- 여러개 프로세스를 컨테이너에 묶을수 없기 때문에 Pod가 등장한것임!

### Service
- 서비스 단위로 pod을 묶어서 관리한다. 그 pod간에 로드밸런싱을 통해서 외부로 서비스를 제공하는 형태
- Pod ip는 내부ip이고 지속적으로 변경되기 떄문에 밖에서 접근이 어려운데 cluster ip(?)를 활용하면 외부에서 접근이 가능하고, 로드밸런싱을제공해준다.
- 같은 파드들을 묶기 위해선 라벨과 라벨 셀럭터를 설정하여 하나의 서비스로 묶어준다. 

### Volume
- 컨테이너가 동작할때 로컬디스크 생성되는데 이건 영구적이지 않지만, Volume은 컨테이너 재시작과 무관하다.
- Pod의 lifecycle을 따른다
- 컨테이너의 외장디스크로 생각하면됨
- pod내에 공유가능하다
- 단일포드는 여러 유형의 여러 볼륨을 동시에 이용 가능함.
#### ASIS
![image](https://user-images.githubusercontent.com/7286378/87272380-08bde500-c511-11ea-8028-d474d5eccbc2.png)

#### TOBE
![image](https://user-images.githubusercontent.com/7286378/87272357-f93e9c00-c510-11ea-89f5-6a9a5e6b7668.png)

#### [Volume 종류](https://kubernetes.io/docs/concepts/storage/#types-of-volumes)
- emptyDir : 일시적인 데이터를 저장하는데 사용되는 비어있는 단순 디렉토리
- hostPath : 워커노드의 파일 시스템에서포드로 디렉터리를 마운트하는데 사용함.
   - 영구 스토리지임
   - 그렇다고 DB storage path론 적합하지 않음
   - 팁 : 노드에서 시스템 파일을 읽거나 써야할때만 쓰고, 포드 전체에 걸쳐 데이터를 유지하기 위해선 사용 ㄴㄴ
- gitRepo  등등

#### 그럼  영구 스토리지는 어떻게 써?
- NAS 유형에 저장해서 사용한다.
- AWS EBS, gcePersistentDisk 등을 쓰면 된다함;;ㅎㅎ

### Namespace
- 클러스터내의 논리적 분리 단위이므로 서로 통신 가능함.
- 리눅스 네임스페이스와 다른 개념이다
- dev/test/real 식으로 분리해서 리소스 할당량을 지정할수 있음. 
- 사용자별 접근 권한 제한 가능
- 논리적 구분단위이기 때문에 엄격하게 하려면 클러스터 분리로 간다.
- [best practice](https://cloudplatform.googleblog.com/2018/04/Kubernetes-best-practices-Organizing-with-Namespaces.html)

### Label
- 쿠버네티스의 리소스를 선택하는데 사용, 각 리소스는 라벨을 가질수 있음
- 라벨을 선택하여 특정 리소스만 배포하거나 업데이트 할수 있고 Service에 연결하거나 특정 네트워크 권한을  부여할 수 있고 다양하게 활용 가능함.
- 하나 이상의 라벨을 적용 할수 있음
- 컨테이너 관리를 해준다는거 k8s라 했는데 이런 라벨을 이용해서 편하게 할수 있다
- Pod 뿐만 아니라 모든 오브젝트에 설정 가능하다.

**Comment by kgneng2** [comment]
## ConfigMap 이란?
- 파일을 이미지로 굽는 작업을 설정을 변경할때마다 이미지를 다시만들어야 하기때문에, 분리한다.
- ```command,  args ``` 설정 값을 통해 docker 의 CMD, ENTRYPOINT를 재정의 가능한데 command는 보통 안씀
- Pod의 이름으로 ConfigMap을 참조한다.
- 최대한 k8s에 종속적이지 않아야 한다.
- 존재하지 않은 Configmap을 참조할 경우에는 컨테이너는 시작하지 않지만 생성을 하면 알아서 pod가 뜸.

##  ConfigMap 생성 방법

### ```$ kubectl create -f abc.yaml ```
```yaml
apiVersion: v1
data:
  send.url: "send.navercorp.com"
  send.roomId: "12345"
kind: ConfigMap
metadata:
  name : dev-stream # 이름을 통해 참조함.
```

### ```$ kubectal create configmap dev-stream --from-file = application.conf```

## configmap in spring boot 
https://dzone.com/articles/configuring-spring-boot-on-kubernetes-with-configm

**Comment by kgneng2** [comment]
## Container Resource 관리에 대해서
> JVM 옵션을 베어메탈에서 돌릴땐 적용했는데 Container 환경에선 이걸 적용해야되나 싶어서 찾아보게 되었음

## JVM Memory Settings in a Container Environment
https://medium.com/adorsys/jvm-memory-settings-in-a-container-environment-64b0840e1d9e

- Java 8u191  부터는 -XX:+UseContainerSupport 지원하는듯 하다. JVM이 cgroup limit을 읽어서 CPU, RAM을 적절하게 적용한다. 이렇게하면 container가 죽는거 대신에 OOM으로 죽게한다고?..... 
- ``` -XX:MaxRAMPercentage``` 이걸 사용하면 -Xmx, -Xms 무시한다
- JVM은 Java 9/8u131 부터 cgroup limit 읽을수 있고 메모리 사용량을 적용한다.
- 하지만 ```-XX:+UseCGroupMemoryLimitForHeap```을 필요한다.
- -XX:MaxRAMFraction=1 으로 OOM을 피할수 있음.

## Assign Memory Resources to Containers and Pods
- namespace 로 구분할듯..
- pod spec container에 다음과 같은것을 넣을수 있음.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
  namespace: mem-example
spec:
  containers:
  - name: memory-demo-2-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
```
이렇게 되면 OOM으로 죽게 된다.
```
NAME            READY     STATUS      RESTARTS   AGE
memory-demo-2   0/1       OOMKilled   1          24s
```
- 노드보다 큰 메모리를 주면 아예 뜨지도 않음

### reference
- https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/

**Comment by kgneng2** [comment]
# YAML 작성 방법
```yaml
apiVersion: apps/v1  # for versions before 1.9.0 use apps/v1beta2 보통 다 apps/v1을 지원함.
kind: Deployment # k8s object/resource type 
metadata: # kind의 metadata  
  name: stream-gate-dsp-v1.0.0-master 
  namespace: plumber
  annotations:
    description: er-dsp event to cq broker dsp_imp_master, dsp_cq_master
spec: # 상세스팩 기입 
  selector:
    matchLabels:
      app: stream-gate-dsp-master
  replicas: 5 # tells deployment to run 2 pods matching the template
  template: 
    metadata:
      labels:
        app: stream-gate-dsp-master
    spec:
      containers:  # container 상세스팩 기입
        - name: stream-gate-dsp-master
          terminationMessagePath: /data/log/stream-gate-termination
          terminationMessagePolicy: File
          imagePullPolicy: Always
          args: ["service/stream-gate-dsp-master.properties", "service/log4j2-default.xml", "dsp-save"]
          image: dev.registry.navercorp.com/bizcloud/stream-gate-sspclient:1.2.7.1
          volumeMounts: # volume 정보 기입
            - name: log-path
              mountPath: log
            - name: state-path
              mountPath: /data/log/kafka-streams
      volumes: # volume spec 기입
        - name: log-path
          hostPath:
            path: /data/log/stream-gate
            type: Directory
        - name: state-path
          hostPath:
            path: /data/log/kafka-streams
            type: Directory
```

**Comment by kgneng2** [comment]
# deploy platform
## overview
- 소스 코드를 수정한 후, 
- 수정한 코드를 컴파일 한 다음에
- 컴파일한 소스 코드를 포함해서 Dockerfile을 이용 or jib 컨테이너로 패키징 한후에
- 컨테이너를 레파지토리 새로운 버전 태그를 붙여서 업로드 하고
- 쿠버네티스의 기존 Deployment나 Pod의 yaml 파일에 image 명을 바꾼후
- kubectl -f apply 를 이용해서 변경된 파일을 반영하고,
- 다음 public IP가 있는 서비스의 경우에는 public IP로 접속하고, 아닌 경우에는 SSH 터널링을 이용해서 해당 Pod나 Service에 접근해서 테스트를 한다.

> ~~아 뭐가 이렇게 많아..~~

## [Skaffold](https://skaffold.dev/)
![image](https://media.oss.navercorp.com/user/1592/files/672dec00-0083-11ea-9877-c67ed28df9c4)
- 실행되면 git or local directory monitoring 
- **소스코드의 변화가 생기면 자동으로 코드를 빌드하고 이를 container packaging을 진행한다**
- tag는 sha256 or commitID
- 미리 정의된 k8s yml 을 이용해서 변경 내용을 k8s cluster에 반영한다.


## Skaffold 설정 파일의 구조
###  Pipeline config
우리가 앞에서 살펴본 skaffold.yaml 파일이 파이프라인 설정 파일에 해당한다. 
컨테이너 빌드 및 레지트리 등록, 테스트 및 컨테이너 배포 일련의 파이프라인에 대한 행동을 정의한다. 

### Global config
~/.skaffold/config 파일에 저장되어 있는 정보로 skaffold의 기본 설정 정보를 정의한다. 예를 들어 디폴트 도커 레지스트리 경로등을 정의한다. 

![image](https://media.oss.navercorp.com/user/1592/files/f5639b80-009e-11ea-94e0-4028fbf4857b)

### builder
- 로컬 docker, Dockerfile 등을 이용해 빌드를 할 수 있으나 우리는 jib으로 빌드한다.

### tagger 
- git commit ID를 이용하는것이 좋아보임.

### test
- 어플리케이션 테스트가 아니고, 컨테이너가 제대로 배포된지 확인하는 작업
- https://github.com/GoogleContainerTools/container-structure-test 를 이용해서 테스트 진행한다고함.

### deploy
- kubectl, helm 등 지원한다.
- Helm과 Skaffold를 이용하면 장점이 Helm의 버전 관리를 이용해서 버전 관리가 간편해지고, 리소스를 삭제할때도 Helm이 의존되는 리소스를 모두 같이 삭제해주기 때문에 깔끔한 배포 및 자원 관리가 가능하다. 

### 요점 정리(?)
- source를 모니터링 하며 변경분이 있으면 이를 빌드 배포를 다 진행해줌. k8s deploy trigger!!?!
- 테스트를 진행해보고 문제가 있는 지 확인한다.

### profile
```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
 artifacts:
 - image: gcr.io/terrycho-personal/node-example
   context: backend
   sync:
     manual:
     # Sync all the javascript files that are in the src folder
     # with the container src folder
     - src: 'src/**/*.js'
       dest: .
profiles:
- name : dev
 build:
   local:
     push: false
- name : production
```

### how to use
#### required
- skaffold
- kubectl
- k8s


### [quick start](https://skaffold.dev/docs/quickstart/)



## [google cloud code](https://cloud.google.com/code/?hl=ko)
- 클라우드 기반 애플리케이션을 쉽고 빠르게 작성, 배포, 디버그 하는 플랫폼
- visual Code, intellij plugin 제공
- IDE용 Cloud Code에서는 Skaffold, Jib, Kubectl 등 자주 사용되는 도구를 통해 코드에 대한 꾸준한 피드백을 실시간으로 확보할 수 있습니다
- 프로덕션 클러스터로 작업할 때 Skaffold 프로필, Kustomize 기반 환경 관리, Cloud Build 통합이 지원됩니다.
- 기본으로 제공되는 IDE 디버깅 기능을 활용해 Visual Studio Code용 및 IntelliJ용 Cloud Code로 IDE에서 코드를 디버그할 수 있습니다.

### how to use
#### required
- [kubectl install](https://kubernetes.io/docs/tasks/tools/install-kubectl/)
- IntelliJ Ultimate 또는 Community
- Skaffold
- [install IDE plugin](https://cloud.google.com/code/docs/intellij/install?hl=ko)
- Tools(도구) > Cloud Code > Kubernetes > Add Kubernetes Support(Kubernetes 지원 추가)

## 의견
- 설치시 이용하면 쉽게 배포 및 디버깅 로깅을 볼 수 있으나, Intellij or vscode 에서만 지원 되기 때문에, 배포 이력 및 리모트 배포가 어렵다.
- 단순히 로컬에서 minikube 설치해서 테스트 용도 외에는 사용 할 수 없다.


## helm
- helm은 ncc를 설치하면 자동으로 설치가 되기 때문에 바로 사용이 가능합니다.
- helm은 쿠버네티스 패키지 매니저 입니다. 쿠버네티스를 사용하다보면 결국 수많은 YAML파일들을 관리해야 됩니다. helm에서는 이런 YAML파일들의 집합을 차트(chart)라고하고, 이 차트를 관리할 수 있게 해주는 도구가 helm입니다

```
차트(chart) : 쿠버네티스 애플리케이션을 만들기위해 필요한 정보들의 묶음입니다.
컨피그(config) : 배포 가능한 객체들을 만들기 위해 패키지된 차트에 넣어서 사용할 수 있는 설정들을 가지고 있습니다.
릴리즈(release) : 특정 컨피그를 이용해서 실행중인 차트의 인스턴스 입니다.

```


## Reference
- https://bcho.tistory.com/1342
